-- What a model costs, as told to us by the person running the instance.
--
-- The migration creates the table and puts nothing in it. A price list shipped in the repository
-- would be wrong within months and nobody would notice — it would keep showing confident sums at
-- last year's rates. Empty means the app says "no price for this model" until somebody supplies
-- one, which is the honest version of not knowing.
--
-- Nothing is ever seeded here either, so there is nothing for a later migration to overwrite: the
-- rows belong entirely to the operator.
--
-- Prices are per million tokens because that is how providers publish them, and numeric rather than
-- floating point because money that drifts in the sixth decimal is money reported wrongly.
-- Input and output are separate for the reason the token columns are separate: providers charge
-- different rates for what they read and what they write.
--
-- (provider, model) is the key. A model name is only unique within a vendor, and two vendors
-- serving the same open model at different prices is the ordinary case, not the exotic one.

create table model_prices
(
    id                  bigint generated by default as identity primary key,
    provider            varchar(32)    not null,
    model               varchar(255)   not null,
    input_per_million   numeric(12, 4) not null,
    output_per_million  numeric(12, 4) not null,
    updated_at          timestamp      not null,
    constraint uq_model_prices_model unique (provider, model)
);
