-- Asking for a bigger ceiling, and the answer.
--
-- One row per request rather than a flag on the user, because the interesting thing is the sequence:
-- who asked, when, what was decided and by whom. A boolean would answer "is somebody waiting" and
-- lose everything else the first time it was cleared.
--
-- `new_limit` records what the limit *became* on approval rather than being read back from the user
-- later. The limit moves again afterwards — that is the whole point of it — and a notification that
-- said "raised to $50" by looking at today's value would eventually say something that never
-- happened.
--
-- `seen_at` is what makes the notification happen once. It is on the request rather than on the
-- user because it is this decision that has been read, not decisions in general.
--
-- Deleting a person takes their requests with them: unlike a run, a request is not a record of work
-- done, and an approval addressed to nobody is not worth keeping. Their *spending* stays in the
-- audit, which is the part that had to survive.

create table budget_requests
(
    id           bigint generated by default as identity primary key,
    user_id      bigint      not null,
    requested_at timestamp   not null,
    status       varchar(16) not null,
    decided_by   bigint,
    decided_at   timestamp,
    new_limit    numeric(12, 4),
    seen_at      timestamp,
    constraint fk_budget_requests_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_budget_requests_decider foreign key (decided_by) references users (id) on delete set null,
    constraint ck_budget_requests_status check (status in ('PENDING', 'APPROVED', 'DECLINED'))
);

-- One person cannot have two requests waiting at once. Enforced here rather than only in the
-- service, because "check then insert" is two statements and two people clicking twice is not a
-- hypothetical on a shared instance.
create unique index ux_budget_requests_one_pending
    on budget_requests (user_id)
    where status = 'PENDING';

create index ix_budget_requests_status on budget_requests (status);
