-- The schema as Hibernate's `ddl-auto: update` left it, captured so that every change from here on
-- is a migration rather than a silent alteration of somebody's database. Generated from the mappings
-- (schema-generation against a real PostgreSQL), then given readable constraint names.
--
-- Databases that already hold this schema never run this file: `baseline-on-migrate` marks them at
-- version 1 and starts them at V2. It runs only on an empty database.

create table job_records
(
    id                     bigint generated by default as identity primary key,
    created_at             timestamp(6) not null,
    processing_started_at  timestamp(6),
    processing_finished_at timestamp(6),
    instruction            text         not null,
    input_filename         varchar(255) not null,
    input_file_path        varchar(255) not null,
    result_file_path       varchar(255),
    status                 varchar(255) not null,
    error_message          text,
    constraint ck_job_records_status check (status in ('PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED'))
);

create table action_results
(
    id              bigint generated by default as identity primary key,
    job_id          bigint       not null,
    execution_order integer      not null,
    action_type     varchar(255) not null,
    description     text,
    success         boolean      not null,
    error_message   text,
    constraint fk_action_results_job foreign key (job_id) references job_records
);

create table chat_sessions
(
    id                varchar(255) not null primary key,
    created_at        timestamp(6) not null,
    last_activity_at  timestamp(6) not null,
    original_filename varchar(255) not null,
    directory         varchar(255) not null,
    current_revision  integer      not null
);

create table chat_messages
(
    id             bigint generated by default as identity primary key,
    session_id     varchar(255) not null,
    role           varchar(255) not null,
    content        text,
    created_at     timestamp(6) not null,
    revision_after integer,
    constraint fk_chat_messages_session foreign key (session_id) references chat_sessions,
    constraint ck_chat_messages_role check (role in ('USER', 'ASSISTANT', 'SYSTEM'))
);

create table chat_steps
(
    id              bigint generated by default as identity primary key,
    message_id      bigint       not null,
    execution_order integer      not null,
    tool_name       varchar(255) not null,
    human_text      text,
    args_json       text,
    result_preview  text,
    success         boolean      not null,
    error_message   text,
    mutating        boolean      not null,
    constraint fk_chat_steps_message foreign key (message_id) references chat_messages
);

create table llm_settings
(
    id            bigint       not null primary key,
    settings_json text         not null,
    updated_at    timestamp(6) not null
);
