-- First iteration on purpose: who a person is, and nothing about what they may do. There is no
-- login yet, so no roles, no sessions and no tokens — those arrive with the code that needs them.
--
-- The column is `password_hash`, not `password`, so that nobody reaches this table intending to
-- store what the user typed. `name` is unique because the whole point of the next migration is
-- answering "who ran this job", and two people called the same thing make that unanswerable.

create table users
(
    id            bigint generated by default as identity primary key,
    name          varchar(255) not null,
    password_hash varchar(255) not null,
    constraint uq_users_name unique (name)
);
