-- What a signed-in session is made of.
--
-- The access token is a JWT and is not stored anywhere: it is short-lived and self-describing, and
-- a table of them would be a table nobody reads.
--
-- The refresh token is the opposite and deliberately NOT a JWT. Deleting a user, or a person
-- pressing "sign out everywhere", has to take effect at once — and a signed token cannot be
-- withdrawn, only waited out. So it is 256 random bits with a row behind it, and the row is what
-- authority actually rests on.
--
-- Only the hash is stored, and SHA-256 rather than bcrypt: the value is already 256 bits of
-- randomness, so there is nothing for a slow hash to protect against guessing, and lookup happens
-- on every refresh. A leaked database still yields no usable token.
--
-- used_at and revoked_at are separate because they mean different things. Rotation marks the old
-- token used; sign-out and user deletion mark tokens revoked. A token presented after it was
-- already used is the signature of a stolen one being replayed, and keeping the two apart is what
-- lets that be recognised rather than merely refused.

create table refresh_tokens
(
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null,
    token_hash  varchar(64)  not null,
    created_at  timestamp    not null,
    expires_at  timestamp    not null,
    remember_me boolean      not null default false,
    used_at     timestamp,
    revoked_at  timestamp,
    constraint uq_refresh_tokens_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id) references users (id) on delete cascade
);

-- Cascade here, unlike job_records: a token is not a record of something that happened, it is a way
-- in. When the person is gone it must stop working, not linger with a null owner.
create index ix_refresh_tokens_user on refresh_tokens (user_id);

-- The key that signs access tokens, when the operator has not supplied one.
--
-- Generated once and kept, because the alternative is generating it per boot — which logs everyone
-- out on every restart, and would be reported as a bug rather than understood as a policy.
create table auth_secrets
(
    name       varchar(64) primary key,
    secret     varchar(512) not null,
    created_at timestamp    not null
);
