-- Every call to a model, in one place.
--
-- Until now only improve runs recorded what they spent, and only as a total on the run. Chat turns
-- recorded nothing at all, so anybody who edits more by conversation than by the improve flow would
-- see a spend chart showing a fraction of the truth — and the chart would look entirely plausible
-- while doing it.
--
-- A row is one call to a model, not one run or one turn: a run that needs a repair makes two calls
-- and a chat turn makes one per step, and summing rows is then the whole of "how much was spent".
--
-- What was asked for is stored here, but what was *done* is not. The steps already live in
-- action_results and chat_steps, and a second copy could only drift from the first — so this table
-- points at the run or the message and the steps are read from there.
--
-- Both references are nullable because a row belongs to exactly one of them, and both clear rather
-- than cascade: deleting a run or a person must not delete the record that money was spent.

create table llm_usage
(
    id                bigint generated by default as identity primary key,
    kind              varchar(16)  not null,
    user_id           bigint,
    job_id            bigint,
    session_id        varchar(64),
    prompt            text,
    prompt_tokens     bigint,
    completion_tokens bigint,
    total_tokens      bigint,
    provider_mode     varchar(16),
    provider          varchar(32),
    model             varchar(255),
    started_at        timestamp    not null,
    finished_at       timestamp    not null,
    constraint fk_llm_usage_user foreign key (user_id) references users (id) on delete set null,
    constraint fk_llm_usage_job foreign key (job_id) references job_records (id) on delete set null
);

create index ix_llm_usage_started on llm_usage (started_at);
create index ix_llm_usage_user on llm_usage (user_id);
create index ix_llm_usage_provider on llm_usage (provider);

-- Chat had no owner at all: sessions belonged to nobody, so "who spent this" was unanswerable for
-- every chat turn. Same rules as a run's owner — nullable for the sessions that predate this and
-- for instances with no accounts, and clearing rather than cascading.
alter table document_sessions
    add column user_id bigint;

alter table document_sessions
    add constraint fk_document_sessions_user foreign key (user_id) references users (id) on delete set null;
